[tool.poetry]
name = "bookwyrm"
version = "0.1.0"
description = ""
authors = ["Mouse Reeve <mousereeve@riseup.net>"]

packages = [ { include = "bookwyrm"}, { include = "celerywyrm" } ]

[tool.poetry.dependencies]
python = "^3.9"
celery = "4.4.2"
colorthief = "0.2.1"
Django = "^3.2"
django-imagekit = "4.0.2"
django-model-utils = "4.0.0"
environs = "9.3.4"
flower = "0.9.7"
Markdown = "3.3.3"
Pillow = "^8.2.0"
psycopg2 = "2.8.4"
pycryptodome = "3.9.4"
python-dateutil = "2.8.1"
redis = "3.4.1"
requests = "2.22.0"
responses = "0.10.14"
django-rename-app = "0.1.2"
pytz = "^2021.1"
gunicorn = "20.0.4"
boto3 = "^1.17"
django-storages = "^1.11"

[tool.poetry.dev-dependencies]
black = { version = "^20.8b1",  allow-prereleases = true}
coverage = "5.1"
pytest-django = "4.1.0"
pytest = "6.1.2"
pytest-cov = "2.10.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
